### ISSUE TITLE
WordPress 5.0 Gutenberg - Post does not save

### ISSUE THREAD

**Issue by tedgeving** [justinwhall/wp-buildhook-deploy#3]
Not sure if this a plugin issue or something to do with Gutenberg.  Post does not save when the metabox options are checked.

`Uncaught (in promise) 
Response
body: (...)
bodyUsed: false
headers: Headers {}
ok: false
redirected: false
status: 500
statusText: "Internal Server Error"
type: "basic"
url: "http://gab-ci.s202372.gridserver.com/wp-admin/post.php?post=8&action=edit&meta-box-loader=1&_wpnonce=651ae8d20b&_locale=user"
__proto__: Response`

`999/wp-json/wp/v2/posts/8/autosaves?_locale=user:1 Failed to load resource: the server responded with a status of 403 (Forbidden)`

`Failed to load resource: the server responded with a status of 400 (Bad Request)`

**Comment by justinwhall** [comment]
This does not appear be related to the plugin. Are you saying the actual posts are not being saved or are not triggering builds?

**Comment by geocine** [comment]
I am getting a `500` as well using this plugin with Gutenberg . Unfortunately I  am on a basic wordpress hosting where I don't have access to php logs. I will try to reproduce on an isolated environment where I have access to logs.

**Comment by geocine** [comment]
This also happens on v4.9.8 of wordpress

```
Only HTTP(S) requests are handled. - /wp-includes/class-requests.php:564
#11 /wp-includes/class-requests.php:363 - Requests::set_defaults('', Array[0], Array[0], 'POST', Array[19])
#10 /wp-includes/class-requests.php:268 - Requests::request('', Array[0], Array[0], 'POST', Array[19])
#9 /wp-content/plugins/littlebot-netlify-master/includes/class-lbn-netlifly.php:64 - Requests::post('')
#8 /wp-content/plugins/littlebot-netlify-master/includes/class-lbn-post.php:145 - LBN_Netlifly->call_build_hook()
#7 /wp-includes/class-wp-hook.php:286 - LBN_Post->save_post(5, WP_Post, true)
#6 /wp-includes/class-wp-hook.php:310 - WP_Hook->apply_filters(5, Array[3])
#5 /wp-includes/plugin.php:453 - WP_Hook->do_action(Array[3])
#4 /wp-includes/post.php:3673 - do_action('save_post', 5, WP_Post, true)
#3 /wp-includes/post.php:3746 - wp_insert_post(Array[57], false)
#2 /wp-admin/includes/post.php:377 - wp_update_post(Array[55])
#1 /wp-admin/post.php:194 - edit_post()
```

There is no url passed even though I have on configured. I do not have any URL in `stage`, on the post I only check `production`

**Comment by geocine** [comment]
I fixed mine, I just made sure I have a build hook for both `stage` and `production` .
