### ISSUE TITLE
Utilize GitHub Releases

### ISSUE THREAD

**Issue by DylanTackoor** [justinwhall/wp-buildhook-deploy#4]
If you add a release to the GitHub page (I believe you just need to make a git tag), I could utilize [TGM-Plugin-Activation](https://github.com/TGMPA/TGM-Plugin-Activation) to bundle the plugin with a theme.

**Comment by justinwhall** [comment]
That's no problem. As of right now, there really hasn't been any releases aside from the master branch I used for Speaking at a WordPress meetup.
