### ISSUE TITLE
Error thrown without defined hook

### ISSUE THREAD

**Issue by braco** [justinwhall/wp-buildhook-deploy#6]
Only entered production hook

Plugin was throwing errors and breaking updates

Temporary fix: enter garbage URL for staging

**Comment by AfroDevGirl** [comment]
Up voting this issue, I ran into the same exact problem (no need for a staging environment so I didn't configure it). Putting in any old url for staging in the plugin setting fixes this problem.

**Comment by geocine** [comment]
Right this was the error I was getting https://github.com/justinwhall/littlebot-netlify/issues/3#issuecomment-467494159

**Comment by justinwhall** [comment]
Never intended this plugin to be used with one environment but no reason it can't be. Easy enough to add some logic here.

**Comment by geocine** [comment]
@justinwhall , what is the intention of the checkbox on the sidebar of the post/page ? Is it a call to action, to publish to that environment? 

Or it is just an indicator to where it is published? Because I checked the code , seems like you intent the latter. However, to a user like me I expect the former.

I am asking so I know what I would do.

**Comment by justinwhall** [comment]
Hey @geocine - To me, both scenarios you are describing sound like the same to me :) I assume I'm not following correctly. 

Here is what happens:

1. If the checkbox is checked, at meta value is added to the post on publish. If it's state it's `lbn_published_stage` if it's prod, it's `lbn_published_production`.
2. Later, when Gatsby builds the site we a var is passed to the build command to tell Gatsby to only build the posts(and pages) the have correct meta value. ie, `DEPLOY_ENV=lbn_published_production gatsby develop` would build prod posts(and pages).

**Comment by justinwhall** [comment]
BTW, this plugin now supports only using one build hook.
