### ISSUE TITLE
Uncaught ArgumentCountError: Too few arguments to function LBN_Post::save_post()

### ISSUE THREAD

**Issue by braco** [justinwhall/wp-buildhook-deploy#8]
Email from Wordpress:

> Howdy!
> 
> Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.
> 
> In this case, WordPress caught an error with one of your plugins, littlebot-netlify.
> 
> First, visit your website ... and check for any visible issues.
> 
> Please contact your host for assistance with investigating this issue further.
> 
> If your site appears broken and you can't access your dashboard normally, WordPress now has a special "recovery mode". This lets you safely login to your dashboard and investigate further.
> 
> Error Details
> =============
> An error of type E_ERROR was caused in line 125 of the file /wordpress-site/wp-content/plugins/littlebot-netlify-master/includes/class-lbn-post.php. Error message: Uncaught ArgumentCountError: Too few arguments to function LBN_Post::save_post(), 1 passed in /wordpress/core/5.2/wp-includes/class-wp-hook.php on line 286 and exactly 3 expected in /wordpress-site/wp-content/plugins/littlebot-netlify-master/includes/class-lbn-post.php:125
> Stack trace:
> #0 /wordpress/core/5.2/wp-includes/class-wp-hook.php(286): LBN_Post->save_post(1115)
> #1 /wordpress/core/5.2/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
> #2 /wordpress/core/5.2/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
> #3 /wordpress/core/5.2/wp-includes/post.php(2864): do_action('delete_post', 1115)
> #4 /wordpress/core/5.2/wp-includes/revision.php(432): wp_delete_post(1115)
> #5 /wordpress/core/5.2/wp-admin/edit-form-blocks.php(302): wp_delete_post_revision(1115)
> #6 /wordpress/core/5.2/wp-admin/post.php(178): include('/wordpress/core...')
> #7 {main}
>   thrown
>

**Comment by justinwhall** [comment]
Hey @braco - Just released 0.9.1. which adds support for PHP 7.3 and patches this issue.
